// source: validations.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.validations.LedgerRangeRequest', null, global);
goog.exportSymbol('proto.validations.LedgerRequest', null, global);
goog.exportSymbol('proto.validations.MasterKeyRequest', null, global);
goog.exportSymbol('proto.validations.ValidationResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.validations.LedgerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.validations.LedgerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.validations.LedgerRequest.displayName = 'proto.validations.LedgerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.validations.LedgerRangeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.validations.LedgerRangeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.validations.LedgerRangeRequest.displayName = 'proto.validations.LedgerRangeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.validations.MasterKeyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.validations.MasterKeyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.validations.MasterKeyRequest.displayName = 'proto.validations.MasterKeyRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.validations.ValidationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.validations.ValidationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.validations.ValidationResponse.displayName = 'proto.validations.ValidationResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.validations.LedgerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.validations.LedgerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.validations.LedgerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.validations.LedgerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerIndex: jspb.Message.getFieldWithDefault(msg, 1, 0),
    requestingNode: jspb.Message.getFieldWithDefault(msg, 14, ""),
    requestingHost: jspb.Message.getFieldWithDefault(msg, 15, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.validations.LedgerRequest}
 */
proto.validations.LedgerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.validations.LedgerRequest;
  return proto.validations.LedgerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.validations.LedgerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.validations.LedgerRequest}
 */
proto.validations.LedgerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLedgerIndex(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestingNode(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestingHost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.validations.LedgerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.validations.LedgerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.validations.LedgerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.validations.LedgerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerIndex();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeString(
      14,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeString(
      15,
      f
    );
  }
};


/**
 * optional uint32 ledger_index = 1;
 * @return {number}
 */
proto.validations.LedgerRequest.prototype.getLedgerIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.validations.LedgerRequest} returns this
 */
proto.validations.LedgerRequest.prototype.setLedgerIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string requesting_node = 14;
 * @return {string}
 */
proto.validations.LedgerRequest.prototype.getRequestingNode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.LedgerRequest} returns this
 */
proto.validations.LedgerRequest.prototype.setRequestingNode = function(value) {
  return jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.validations.LedgerRequest} returns this
 */
proto.validations.LedgerRequest.prototype.clearRequestingNode = function() {
  return jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.validations.LedgerRequest.prototype.hasRequestingNode = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional string requesting_host = 15;
 * @return {string}
 */
proto.validations.LedgerRequest.prototype.getRequestingHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.LedgerRequest} returns this
 */
proto.validations.LedgerRequest.prototype.setRequestingHost = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.validations.LedgerRequest} returns this
 */
proto.validations.LedgerRequest.prototype.clearRequestingHost = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.validations.LedgerRequest.prototype.hasRequestingHost = function() {
  return jspb.Message.getField(this, 15) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.validations.LedgerRangeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.validations.LedgerRangeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.validations.LedgerRangeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.validations.LedgerRangeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerIndexMin: jspb.Message.getFieldWithDefault(msg, 1, 0),
    ledgerIndexMax: jspb.Message.getFieldWithDefault(msg, 2, 0),
    requestingNode: jspb.Message.getFieldWithDefault(msg, 14, ""),
    requestingHost: jspb.Message.getFieldWithDefault(msg, 15, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.validations.LedgerRangeRequest}
 */
proto.validations.LedgerRangeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.validations.LedgerRangeRequest;
  return proto.validations.LedgerRangeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.validations.LedgerRangeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.validations.LedgerRangeRequest}
 */
proto.validations.LedgerRangeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLedgerIndexMin(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLedgerIndexMax(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestingNode(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestingHost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.validations.LedgerRangeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.validations.LedgerRangeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.validations.LedgerRangeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.validations.LedgerRangeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerIndexMin();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getLedgerIndexMax();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeString(
      14,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeString(
      15,
      f
    );
  }
};


/**
 * optional uint32 ledger_index_min = 1;
 * @return {number}
 */
proto.validations.LedgerRangeRequest.prototype.getLedgerIndexMin = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.validations.LedgerRangeRequest} returns this
 */
proto.validations.LedgerRangeRequest.prototype.setLedgerIndexMin = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 ledger_index_max = 2;
 * @return {number}
 */
proto.validations.LedgerRangeRequest.prototype.getLedgerIndexMax = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.validations.LedgerRangeRequest} returns this
 */
proto.validations.LedgerRangeRequest.prototype.setLedgerIndexMax = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string requesting_node = 14;
 * @return {string}
 */
proto.validations.LedgerRangeRequest.prototype.getRequestingNode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.LedgerRangeRequest} returns this
 */
proto.validations.LedgerRangeRequest.prototype.setRequestingNode = function(value) {
  return jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.validations.LedgerRangeRequest} returns this
 */
proto.validations.LedgerRangeRequest.prototype.clearRequestingNode = function() {
  return jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.validations.LedgerRangeRequest.prototype.hasRequestingNode = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional string requesting_host = 15;
 * @return {string}
 */
proto.validations.LedgerRangeRequest.prototype.getRequestingHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.LedgerRangeRequest} returns this
 */
proto.validations.LedgerRangeRequest.prototype.setRequestingHost = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.validations.LedgerRangeRequest} returns this
 */
proto.validations.LedgerRangeRequest.prototype.clearRequestingHost = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.validations.LedgerRangeRequest.prototype.hasRequestingHost = function() {
  return jspb.Message.getField(this, 15) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.validations.MasterKeyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.validations.MasterKeyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.validations.MasterKeyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.validations.MasterKeyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    masterKey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    requestingNode: jspb.Message.getFieldWithDefault(msg, 14, ""),
    requestingHost: jspb.Message.getFieldWithDefault(msg, 15, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.validations.MasterKeyRequest}
 */
proto.validations.MasterKeyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.validations.MasterKeyRequest;
  return proto.validations.MasterKeyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.validations.MasterKeyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.validations.MasterKeyRequest}
 */
proto.validations.MasterKeyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMasterKey(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestingNode(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestingHost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.validations.MasterKeyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.validations.MasterKeyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.validations.MasterKeyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.validations.MasterKeyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMasterKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeString(
      14,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeString(
      15,
      f
    );
  }
};


/**
 * optional string master_key = 1;
 * @return {string}
 */
proto.validations.MasterKeyRequest.prototype.getMasterKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.MasterKeyRequest} returns this
 */
proto.validations.MasterKeyRequest.prototype.setMasterKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string requesting_node = 14;
 * @return {string}
 */
proto.validations.MasterKeyRequest.prototype.getRequestingNode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.MasterKeyRequest} returns this
 */
proto.validations.MasterKeyRequest.prototype.setRequestingNode = function(value) {
  return jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.validations.MasterKeyRequest} returns this
 */
proto.validations.MasterKeyRequest.prototype.clearRequestingNode = function() {
  return jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.validations.MasterKeyRequest.prototype.hasRequestingNode = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional string requesting_host = 15;
 * @return {string}
 */
proto.validations.MasterKeyRequest.prototype.getRequestingHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.MasterKeyRequest} returns this
 */
proto.validations.MasterKeyRequest.prototype.setRequestingHost = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.validations.MasterKeyRequest} returns this
 */
proto.validations.MasterKeyRequest.prototype.clearRequestingHost = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.validations.MasterKeyRequest.prototype.hasRequestingHost = function() {
  return jspb.Message.getField(this, 15) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.validations.ValidationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.validations.ValidationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.validations.ValidationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.validations.ValidationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    cookie: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, ""),
    flags: jspb.Message.getFieldWithDefault(msg, 3, 0),
    full: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    ledgerHash: jspb.Message.getFieldWithDefault(msg, 5, ""),
    ledgerIndex: jspb.Message.getFieldWithDefault(msg, 6, 0),
    masterKey: jspb.Message.getFieldWithDefault(msg, 7, ""),
    signature: jspb.Message.getFieldWithDefault(msg, 8, ""),
    signingTime: jspb.Message.getFieldWithDefault(msg, 9, 0),
    validatedHash: jspb.Message.getFieldWithDefault(msg, 10, ""),
    validationPublicKey: jspb.Message.getFieldWithDefault(msg, 11, ""),
    data: jspb.Message.getFieldWithDefault(msg, 12, ""),
    serverVersion: jspb.Message.getFieldWithDefault(msg, 16, ""),
    baseFee: jspb.Message.getFieldWithDefault(msg, 17, 0),
    loadFee: jspb.Message.getFieldWithDefault(msg, 18, 0),
    reserveBase: jspb.Message.getFieldWithDefault(msg, 19, 0),
    reserveInc: jspb.Message.getFieldWithDefault(msg, 20, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.validations.ValidationResponse}
 */
proto.validations.ValidationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.validations.ValidationResponse;
  return proto.validations.ValidationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.validations.ValidationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.validations.ValidationResponse}
 */
proto.validations.ValidationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCookie(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFlags(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFull(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLedgerHash(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLedgerIndex(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setMasterKey(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignature(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSigningTime(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setValidatedHash(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setValidationPublicKey(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setData(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerVersion(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBaseFee(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLoadFee(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setReserveBase(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setReserveInc(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.validations.ValidationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.validations.ValidationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.validations.ValidationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.validations.ValidationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCookie();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFlags();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getFull();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getLedgerHash();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLedgerIndex();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getMasterKey();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getSignature();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getSigningTime();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getValidatedHash();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getValidationPublicKey();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getData();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getServerVersion();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getBaseFee();
  if (f !== 0) {
    writer.writeInt32(
      17,
      f
    );
  }
  f = message.getLoadFee();
  if (f !== 0) {
    writer.writeInt32(
      18,
      f
    );
  }
  f = message.getReserveBase();
  if (f !== 0) {
    writer.writeUint32(
      19,
      f
    );
  }
  f = message.getReserveInc();
  if (f !== 0) {
    writer.writeUint32(
      20,
      f
    );
  }
};


/**
 * optional string cookie = 1;
 * @return {string}
 */
proto.validations.ValidationResponse.prototype.getCookie = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setCookie = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string type = 2;
 * @return {string}
 */
proto.validations.ValidationResponse.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 flags = 3;
 * @return {number}
 */
proto.validations.ValidationResponse.prototype.getFlags = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setFlags = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool full = 4;
 * @return {boolean}
 */
proto.validations.ValidationResponse.prototype.getFull = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setFull = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string ledger_hash = 5;
 * @return {string}
 */
proto.validations.ValidationResponse.prototype.getLedgerHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setLedgerHash = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional uint32 ledger_index = 6;
 * @return {number}
 */
proto.validations.ValidationResponse.prototype.getLedgerIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setLedgerIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string master_key = 7;
 * @return {string}
 */
proto.validations.ValidationResponse.prototype.getMasterKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setMasterKey = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string signature = 8;
 * @return {string}
 */
proto.validations.ValidationResponse.prototype.getSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setSignature = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional uint32 signing_time = 9;
 * @return {number}
 */
proto.validations.ValidationResponse.prototype.getSigningTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setSigningTime = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string validated_hash = 10;
 * @return {string}
 */
proto.validations.ValidationResponse.prototype.getValidatedHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setValidatedHash = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string validation_public_key = 11;
 * @return {string}
 */
proto.validations.ValidationResponse.prototype.getValidationPublicKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setValidationPublicKey = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string data = 12;
 * @return {string}
 */
proto.validations.ValidationResponse.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setData = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string server_version = 16;
 * @return {string}
 */
proto.validations.ValidationResponse.prototype.getServerVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setServerVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional int32 base_fee = 17;
 * @return {number}
 */
proto.validations.ValidationResponse.prototype.getBaseFee = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setBaseFee = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


/**
 * optional int32 load_fee = 18;
 * @return {number}
 */
proto.validations.ValidationResponse.prototype.getLoadFee = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setLoadFee = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * optional uint32 reserve_base = 19;
 * @return {number}
 */
proto.validations.ValidationResponse.prototype.getReserveBase = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setReserveBase = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional uint32 reserve_inc = 20;
 * @return {number}
 */
proto.validations.ValidationResponse.prototype.getReserveInc = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.validations.ValidationResponse} returns this
 */
proto.validations.ValidationResponse.prototype.setReserveInc = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


goog.object.extend(exports, proto.validations);
